Minor change to README.md
javascript-tutorial/vi.javascript.info pull request #203
Opened 2023-05-08 13:10 UTC by ImVietnam

2023-05-28 11:15 UTC, Thai2706 approved these changes

2023-06-07 07:29 UTC, tunggnu commented on README.md
> +- Đừng dịch các biến, class và các mã định danh.
"định danh" ở đây là các tên gọi như tên biến, nên thêm "mã" đằng trước là vô nghĩa

2023-06-07 07:31 UTC, tunggnu requested changes
Hãy xem chú thích về "mã định danh" ở dưới.

2023-06-07 09:14 UTC, ImVietnam commented
/done

2023-06-08 01:07 UTC, tunggnu approved these changes
Good

2023-06-08 01:08 UTC, merged