Functions
javascript-tutorial/vi.javascript.info pull request #222
Opened 2024-07-13 07:10 UTC by hoangnv170752

2024-07-13 07:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/vi.javascript.info?pullRequest=222) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/vi.javascript.info?pullRequest=222) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/vi.javascript.info?pullRequest=222) it.</sub>

2024-07-13 07:12 UTC, hoangnv170752 commented
@tunggnu & @henryonsoftware xin phép ping các anh về phần review và merge ạ

2024-07-13 08:59 UTC, tunggnu requested changes

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/1-if-else-required/task.md
> +# Có thật là từ "else" cần thiết?
"else" có bắt buộc không?

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/solution.md
> +Lưu ý rằng dấu ngoặc đơn quanh `age > 18` thì không được yêu cầu ở đây. Chúng tồn tại để dễ hơn cho việc đọc.
Lưu ý rằng dấu ngoặc đơn quanh `age > 18` là không bắt buộc. Chúng tồn tại để chúng ta dễ đọc hơn.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/3-min/solution.md
> +Tái bút: Trong trường hợp có một phương trình `a == b` thì nó không còn quan trọng việc trả về giá trị gì.
"Tái bút: Trong trường hợp so sánh bằng nhau `a == b` thì không quan trọng  giá trị trả về là gì."

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Từ khoá `function` được bắt đầu trước, sau đó đến *tên của hàm*, và có một danh sách các *tham số* giữa các dấu ngoặc đơn (được phân tách bằng dấu phẩy, trống trong ví dụ trên) và cuối cùng là mã của
1. "(được phân tách bằng dấu phẩy, những cũng có thể để trống như trong ví dụ trên)"
2. còn được gọi là "thân hàm"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Chức năng mới của chúng ta có thể được gọi bằng tên của nó:: `showMessage()`.
"Hàm mới của chúng ta"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Việc gọi `showMessage()` thực thi đoạn mã trong hàm. Ở đây chúng ta sẽ thấy tin nhắn được hiển thị hai lần.
"sẽ thấy thông điệp được hiển thị hai lần"
hoặc:
"sẽ thấy thông báo được hiển thị hai lần"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Một biến được khai báo bên trong một hàm chỉ hiển thị bên trong hàm đó.
"Một biến được khai báo bên trong một hàm chỉ nhìn thấy được từ bên trong hàm đó."

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +alert( message ); // <-- Lỗi! Đây là biến cục bộ so với hàm
"cục bộ đối với hàm"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Hàm có toàn quyền truy cập vào biến ngoài. Nó cũng có thể thay đổi được.
Nó cũng có thể thay đổi được biến ngoài.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Biến ngoài chỉ được sử dụng nếu không có biến cục bộ.
"nếu không có biến cục bộ trùng tên với nó"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Nếu một biến cùng tên được khai báo bên trong hàm thì nó sẽ *che khuất* biến bên ngoài. Ví dụ: trong đoạn mã bên dưới, hàm sử dụng `userName` cục bộ. Cái bên ngoài bị bỏ qua:
"Biến bên ngoài bị bỏ qua:"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Các biến được khai báo bên ngoài bất kỳ hàm nào, chẳng hạn như `userName` bên ngoài trong mã ở trên, được gọi là *toàn cục*.
"chẳng hạn như  biến ngoài `userName` trong mã ở trên"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Các biến toàn cục được hiển thị từ bất kỳ hàm nào (trừ khi bị che bởi cục bộ).
Các biến toàn cục có thể nhìn thấy được từ bất kỳ hàm nào (trừ phi bị che bởi biến cục bộ).

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Đó là một cách thực hành tốt để giảm thiểu việc sử dụng các biến toàn cục. Mã nguồn hiện đại có ít hoặc không có toàn cục. Hầu hết các biến đều nằm trong hàm của chúng. Tuy nhiên, đôi khi chúng có th
Một cách thực hành tốt là giảm thiểu việc sử dụng các biến toàn cục.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Khi hàm được gọi trong các dòng `(*)` và `(**)`, các giá trị đã cho sẽ được sao chép sang các biến cục bộ `from` và `text`. Sau đó, chức năng sử dụng chúng.
Sau đó, hàm sẽ sử dụng chúng.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Đây là một ví dụ nữa: chúng ta có một biến `from` và chuyển nó vào hàm. Xin lưu ý: hàm thay đổi `from`, nhưng sự thay đổi không được nhìn thấy bên ngoài, vì hàm luôn nhận được bản sao của giá trị:
1. "chúng ta có một biến `from` và truyền nó cho hàm"
2. "nhưng sự thay đổi không được nhìn thấy từ bên ngoài"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Nếu một tham số không được cung cấp thì giá trị của nó sẽ trở thành `không xác định`.
Giữ nguyên `undefined`, không dịch thành `không xác định`.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Bây giờ nếu tham số `text` không được truyền, nó sẽ nhận giá trị `"không có văn bản"`
giá trị `"không có văn bản nào được đưa ra"`

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Ở đây `"không có văn bản nào"` là một chuỗi, nhưng nó có thể là một biểu thức phức tạp hơn, chỉ được đánh giá và gán nếu thiếu tham số. Vì vậy, điều này cũng có thể:
Ở đây `"không có văn bản nào được đưa ra"`

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +    text = 'tin nhắn trống';
text = 'tin nhắn rỗng';

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Kết quả là một hàm có thể trả về một giá trị vào mã gọi.
Một hàm có thể trả về một giá trị làm kết quả cho mã gọi hàm đó.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Lệnh `return` có thể ở bất kỳ vị trí nào của hàm. Khi quá trình thực thi đạt đến mức đó, hàm sẽ dừng và giá trị được trả về mã gọi (được gán cho `kết quả` ở trên).
được gán cho `result` ở trên

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Ở đoạn mã ở trên, nếu `checkAge(age)` trả về `false`, sau đó `showMovie` sẽ không dẫn tới `alert`.
nếu `checkAge(age)` trả về `false`, thì `showMovie` sẽ không thực hiện hàm `alert`

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +````smart header="Một hàm trả về giá trị với `return` hoặc không có gì với `undefined`"
smart header="Một hàm trả với `return` rỗng hoặc không có  `return` thì trả về `undefined`"

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Nếu một hàm không trả về một giá trị thì cũng giống như khi nó trả về `undefined`:
thì cũng giống như là nó trả về `undefined`

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Trường hợp `return` thì cũng giống với `return undefined`:
Trường hợp `return` rỗng, không kèm theo giá trị, thì cũng giống với `return undefined`:

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Đối với một biểu thức dài trong `return`, có thể nên đặt nó trên một dòng riêng biệt, như thế này:
Đối với một biểu thức dài trong `return`, có thể bạn muốn đặt nó trên một dòng riêng biệt, như thế này:

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Thông lệ phổ biến là bắt đầu một chức năng bằng tiền tố bằng lời nói mô tả hành động một cách mơ hồ. Phải có sự thống nhất trong nhóm về ý nghĩa của các tiền tố.
Thông lệ phổ biến là bắt đầu một hàm bằng tiền tố động từ mô tả mơ hồ hành động của hàm.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +showMessage(..)     // đưa ra một tin nhắn
một thông báo (hoặc thông điệp)

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Một hàm phải thực hiện chính xác những gì được gợi ý theo tên của nó, không hơn thế nữa.
Một hàm nên thực hiện chính xác những gì được gợi ý theo tên của nó, và không làm gì khác nữa.

2024-07-13 08:59 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Những ví dụ này giả định ý nghĩa chung của tiền tố. Bạn và nhóm của bạn có thể tự do đồng ý về các ý nghĩa khác, nhưng thông thường chúng không khác nhau nhiều. Trong mọi trường hợp, bạn phải hiểu rõ
Và nhóm nên có chung nhận ​​thức.

2024-07-13 09:02 UTC, tunggnu commented
@hoangnv170752 bạn cần ký thỏa thuận tác quyền ở link này https://github.com/javascript-tutorial/vi.javascript.info/pull/222#issuecomment-2226803210

2024-07-13 09:43 UTC, hoangnv170752 reviewed
Em có đẩy 1 commit mới sửa các lỗi dịch ạ

2024-07-13 14:24 UTC, tunggnu requested changes

2024-07-13 14:24 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +- Tên phải mô tả rõ ràng chức năng của nó. Khi chúng ta thấy một lệnh gọi hàm trong mã, một cái tên hay sẽ ngay lập tức giúp chúng ta hiểu nó làm gì và trả về gì.
Đổi "Tên phải mô tả rõ ràng chức năng của nó." thành "Tên hàm nên mô tả rõ hàm thực hiện công việc gì."

2024-07-13 14:24 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Ví dụ: chúng ta cần hiển thị một thông báo đẹp mắt khi khách hàng truy cập đăng nhập, đăng xuất và có thể ở một nơi khác
1. Thay "khi khách hàng **truy cập** đăng nhập, đăng xuất" thành "khi khách hàng đăng nhập, đăng xuất" (bỏ **truy cập** đi, bản gốc không có hai từ này)
2. Thiếu dấu `.` hết câu ở sau "và có thể ở một nơi khác"

2024-07-14 07:27 UTC, tunggnu requested changes

2024-07-14 07:27 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Ví dụ: chúng ta cần hiển thị một thông báo đẹp mắt khi khách hàng khi khách hàng đăng nhập, đăng xuất và có thể ở một nơi khác
1. `khi khách hàng khi khách hàng đăng nhập` <== chỗ này bị lặp cụm từ `khi khách hàng`
2. Thay `và có thể ở một nơi khác` bằng `và có thể ở một nơi khác.` ( thêm dấu `.` hết câu)

2024-07-14 07:27 UTC, tunggnu commented on 1-js/02-first-steps/15-function-basics/article.md
> +Hàm có tham số nhưng không gây tác dụng phụ thì dễ hiểu hơn hàm không tham số nhưng lại gây tác dụng phụ.
Câu `Hàm có tham số nhưng không gây tác dụng phụ thì dễ hiểu hơn hàm không tham số nhưng lại gây tác dụng phụ.` vốn là mình dùng để giải thích cho bạn hiểu hơn ý nghĩa của bản gốc, chứ không phải đem nó làm bản dịch. Bản dịch cần phải như sau mới bám sát bản gốc:

> Một hàm nhận các tham số, sử dụng chúng rồi trả về một kết quả, luôn dễ hiểu hơn một hàm không nhận tham số nào, nhưng lại thay đổi giá trị của các biến ngoài, như một tác dụng phụ.

2024-07-14 07:30 UTC, tunggnu commented
@hoangnv170752 bạn xem lại 3 bình luận của mình ở trên để sửa nội dung tương ứng, sửa xong cái nào bạn bấm **Resolve conversation** để đóng bình luận đó lại.

2024-07-15 03:33 UTC, tunggnu commented
@hoangnv170752 còn bình luận này bạn chưa xử lý https://github.com/javascript-tutorial/vi.javascript.info/pull/222#discussion_r1676818349

2024-07-15 06:15 UTC, hoangnv170752 commented
Em đã hoàn thiện ạ @tunggnu

2024-07-15 06:44 UTC, tunggnu approved these changes

2024-07-15 06:44 UTC, merged